### ISSUE TITLE
shell script plugin set to run as another user (ldap)

### ISSUE THREAD

**Issue by wccropper** [jhuckaby/Cronicle#141]
## Summary
New server. Configured to use LDAP Authentication via PAM. Shel Script Plugin copied and configured for LDAP user. LDAP user can login to the server.

## Steps to reproduce the problem
Summary explains all

### Operating system and version?
CentOS 7.5

### Node.js version?
11.3.0

### Cronicle software version?
0.8.28

### Are you using a multi-server setup, or just a single server?
multi-server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
NFS

### Can you reproduce the crash consistently?
Yes

### Log Excerpts
# Job failed at 2018/12/03 15:25:00 (GMT-6).
# Error: Plugin Error: User does not exist: username
# End of log.

**Comment by wccropper** [comment]
Just looking for an update. Any response is appreciated.

**Comment by jhuckaby** [comment]
I honestly don't know how to help you.  From the error message it looks like you are asking Cronicle to switch to a user named literally `username`:

```
Error: Plugin Error: User does not exist: username
```

I have no idea how to troubleshoot this.  Maybe try running the job as root instead, and then using `sudo` in your shell script to switch to the user you need.

I apologize if this is not helpful, but I have nothing else to go on here.

**Comment by wccropper** [comment]
I sanitized my output (username = the username from LDAP). The basic issue is for cronicle to be of any use to me (and I see great usage options), I need it to recognize users who are in an LDAP. PAM is configured to allow these users to log into the server and a shared /home is mounted. But the user mechanism in use by cronicle seems to only look at the /etc/passwd file rather than interfacing with PAM.

**Comment by jhuckaby** [comment]
Hmm, okay, I think I understand what you're saying.  Unfortunately I've never used LDAP or PAM, so I don't know how they handle user auth under the covers, but I will say this.  The only time Cronicle ever consults the `/etc/passwd` file is to resolve a username (string) to its respective UID (number).  Then it just passes the raw UID number to the Node.js child `spawn()` function.

Can you try specifying your user as a UID (number) instead of a string name?  That would bypass the `/etc/passwd` lookup and pass the value directly to the Node child spawn function.

Also, since you are using the Shell Plugin, you could put all this logic into your shell code itself.  Meaning, just run the Cronicle job as root, then use `sudo` or `su` to switch users inside the shell code.  I am assuming `sudo` and `su` know about LDAP / PAM, and can correctly resolve your username.

Good luck!

**Comment by jhuckaby** [comment]
Fixed by @wccropper!  Thanks!!!

**Comment by frizwi** [comment]
Hi, I have the same issue but not sure I understand how this is fixed?!

Basically by Shell plugin to Run as user never works unless the username is in the /etc/passwd file. Even when specifying the UID instead of the username name, I still get "unkown user: 12345". Any ideas for a work around?

**Comment by jhuckaby** [comment]
Sorry for the confusion -- the bug was fixed in [one of the support libraries](https://github.com/jhuckaby/pixl-tools/pull/1) used by Cronicle.  There hasn't been a new release of Cronicle since then, so if you don't want to wait you can manually install the update.  Try this on all your server(s):

```
cd /opt/cronicle
npm install pixl-tools
bin/control.sh restart
```

**Comment by frizwi** [comment]
Thanks, I did try this but still getting the same error:

# Job failed at 2019/03/01 11:01:42 (GMT+11).
# Error: Plugin Error: User does not exist: trike-dev
# End of log.

Its on a slave server but I've done what you've said below 
on both the master and this slave (but not the other slaves 
- does that matter?)

Running Cronicle version 0.2.28.

-Farhan
